# Generated by Django 2.1.7 on 2019-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='data_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
