# Generated by Django 2.1.7 on 2019-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_datapoint_data_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=100)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('node_name', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
